services:
  the_story:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./the_story:/the_story
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"